FROM nginx:stable-alpine
COPY deploy/nginx-web.conf /etc/nginx/conf.d/default.conf
COPY deploy/nginx-voice.conf /etc/nginx/snippets/voice.conf
RUN sed -i 's@127.0.0.1:4175@voice:4175@' /etc/nginx/snippets/voice.conf
COPY index.html /usr/share/nginx/html/index.html
COPY videos/ /usr/share/nginx/html/videos/
COPY media/ /usr/share/nginx/html/media/
